data:extend(
{ { type = "item", name = "creative-chest", place_result = "creative-chest",
    icon = "__creative-mode__/graphics/icons/creative-chest.png",
    subgroup = "belt", order = "a[items]-b[creative-chest]",
    flags = {"goes-to-quickbar"}, stack_size = 50 },
  { type = "recipe", name = "creative-chest", enabled = "true",
    energy_required = 0, ingredients = {}, result = "creative-chest" },
  { type = "logistic-container",
    name = "creative-chest",
    icon = "__creative-mode__/graphics/icons/item-source.png",
    flags = {"placeable-player", "player-creation"},
    minable = {hardness = 0.2, mining_time = 0.5, result = "creative-chest"},
    max_health = 40,
    corpse = "small-remnants",
    collision_box = {{-0.35, -0.35}, {0.35, 0.35}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
    fast_replaceable_group = "container",
    inventory_size = 109,
    logistic_mode = "requester",
    open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume=0.65 },
    close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
    picture =
    { filename = "__creative-mode__/graphics/entity/item-source/item-source.png",
      priority = "extra-high",
      width = 48,
      height = 34,
      shift = {0.2, 0} } } })
